name: todo_app_v2
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

  flutter_lints: ^5.0.0

flutter:
 
  uses-material-design: true

  